load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "imgui_info_center",
    srcs = ["imgui_info_center.cpp"],
    hdrs = ["imgui_info_center.h"],
    deps = ["//third_party/imgui"],
)
